# Generated by Django 5.1.7 on 2025-03-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHITTAGONG', 'Chittagong'), ('KHULNA', 'Khulna'), ('RAJSHAHI', 'Rajshahi'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('RANGPUR', 'Rangpur'), ('MYMENSINGH', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
